# -*- coding: utf-8 -*-
# © 2017 Open Net Sarl
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    'name': 'Open-Net Customization for Open Net',
    'summary': 'Open Net Customization for Open Net',
    'description': 'Open Net Customization for Open Net',
    'category': 'Open Net customizations',
    'author': "Open Net Sàrl",
    'depends': [
        'account',
        'sale',
        'report',
        'ons_productivity_project_issue',
        'account_reports',
        'website_portal_sale',
        'event_barcode',
        'eagle_project',
        'eagle_base',
        'stock',
        'project_issue',
        'account_budget'
    ],
    'version': '10.0.1.0.2',
    'auto_install': False,
    'website': 'http://open-net.ch',
    'license': 'AGPL-3',
    'images': [],
    'data': [
        'data/ons_cust_crons.xml',
        'data/mail_template.xml',
        'data/res_groups.xml',
        'security/ir.model.access.csv',
        'security/security.xml',
        'report/account_followup_report_views.xml',
        'views/ons_cust_opennet.xml',
        'views/views_project_task.xml',
        'views/views_eagle.xml',
        'views/views_sale.xml',
        'views/views_stock_move.xml',
        'views/views_res_partner.xml',
        'views/report_external_header.xml',
        'views/report_external_footer.xml',
        'views/report_invoice.xml',
        'views/report_event_badge_templates.xml',
        # 'views/report_financial.xml',
        'views/ons_cust_customer_config_views.xml',
        'views/ons_cust_customer_changes_views.xml',
        'views/ons_cust_custumer_config_web_views.xml',
        'views/ons_functionnal_area_view.xml',
        'views/ons_pricing_template.xml',
        'views/ons_pricing_option_view.xml',
        'views/ons_hosting_view.xml',
        'views/ons_area_dependencies_view.xml',
        'views/ons_ir_module_view.xml',
        'views/ons_user_pricing_view.xml',
        'views/ons_pricing_client_view.xml',
        'views/website_portal_templates.xml',
        'views/website_portal_sale_templates.xml',
    ],
    'installable': True
}
